name: "authors_toolbox"
description: A Flutter application for the Authors Toolbox.

# The version of your application.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  reorderables: ^0.6.0
  file_picker: ^8.1.2
  percent_indicator: ^4.0.1
  fl_chart: ^0.69.0
  shared_preferences: ^2.0.9
  path_provider: ^2.0.11
  url_launcher: ^6.0.20
  image_picker: ^1.1.2
  provider: ^6.0.0
  intl: ^0.19.0
  window_manager: ^0.4.2
  process_run: ^1.2.0
  flutter_lints: ^2.0.1
  flutter_secure_storage: ^9.2.2 # Moved to dependencies
  http: ^1.2.2 # Moved to dependencies

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  lint: ^2.0.0

flutter:
  uses-material-design: true

  # Assets to include in the project
  assets:
    - assets/placeholder.png
    - assets/logo.png
    - assets/texture_background.png
    - assets/icon.png

flutter_icons:
  android: true
  ios: true
  windows: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#FFFFFF"  # It's recommended to use a color here
